### ISSUE TITLE
please could you add a permissive licence to the .sql files and examples?

### ISSUE THREAD

**Issue by graingert** [ReneNyffenegger/about-MSSQL#1]
specifically I'm looking to use the dbo.regex_like function - but there's no licence or copyright information.

https://spdx.org/licenses/0BSD.html is great for example snippets 

https://spdx.org/licenses/MIT.html, https://spdx.org/licenses/Apache-2.0.html and https://spdx.org/licenses/BSD-3-Clause.html are all popular licences for software in general

Thanks!

**Comment by ReneNyffenegger** [comment]
Thanks for the suggestion. I have moved the functions to https://github.com/ReneNyffenegger/SQL-Server-helpers/tree/master/regexp and given them the MIT license.
Since I am not used with licensing stuff, please let me know if this is correct, thanks.

**Comment by graingert** [comment]
> Thanks for the suggestion. I have moved the functions to https://github.com/ReneNyffenegger/SQL-Server-helpers/tree/master/regexp and given them the MIT license. Since I am not used with licensing stuff, please let me know if this is correct, thanks.

Amazing thanks a lot!
